---
name: Docker packaging

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  LATEST: "2.13-3.2.0"
  IMAGE_DEST: "ssorriaux/kafka"

jobs:
  build-and-push:
    name: Docker - build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - scala: 2.12
          kafka_version: 2.1.1
        - scala: 2.12
          kafka_version: 2.2.2
        - scala: 2.12
          kafka_version: 2.3.1
        - scala: 2.12
          kafka_version: 2.4.1
        - scala: 2.12
          kafka_version: 2.5.1
        - scala: 2.13
          kafka_version: 2.6.3
        - scala: 2.13
          kafka_version: 2.7.2
        - scala: 2.13
          kafka_version: 2.8.1
        - scala: 2.13
          kafka_version: 3.0.1
        - scala: 2.13
          kafka_version: 3.1.1
        - scala: 2.13
          kafka_version: 3.2.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set some vars
      id: setup
      run: |
        echo BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") >> $GITHUB_OUTPUT
        echo DOCKER_IMAGE_TAG=${{ env.IMAGE_DEST }}:${{ matrix.scala }}-${{ matrix.kafka_version }} >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.setup.outputs.DOCKER_IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          kafka_version=${{ matrix.kafka_version }}
          scala_version=${{ matrix.scala }}
          vcs_ref=${{ github.sha }}
          build_date=${{ steps.setup.outputs.BUILD_DATE }}